import { CoinDetailData } from '@/types/crypto';

export const mockCoinDetails: Record<string, CoinDetailData> = {
  bitcoin: {
    id: 'bitcoin',
    symbol: 'btc',
    name: 'Bitcoin',
    web_slug: 'bitcoin',
    asset_platform_id: null,
    platforms: {},
    detail_platforms: {},
    block_time_in_minutes: 10,
    hashing_algorithm: 'SHA-256',
    categories: ['Crypto'],
    preview_listing: false,
    public_notice: null,
    additional_notices: [],
    description: {
      en: 'Bitcoin is a decentralized digital currency, without a central bank or single administrator, that can be sent from user to user on the peer-to-peer bitcoin network without the need for intermediaries.',
    },
    links: {
      homepage: ['https://bitcoin.org'],
      whitepaper: 'https://bitcoin.org/bitcoin.pdf',
      blockchain_site: [],
      official_forum_url: [],
      chat_url: [],
      announcement_url: [],
      snapshot_url: null,
      twitter_screen_name: 'bitcoin',
      facebook_username: '',
      bitcointalk_thread_identifier: null,
      telegram_channel_identifier: '',
      subreddit_url: 'https://reddit.com/r/bitcoin',
      repos_url: {
        github: ['https://github.com/bitcoin/bitcoin'],
        bitbucket: [],
      },
    },
    image: {
      thumb: '',
      small: '',
      large: '',
    },
    country_origin: '',
    genesis_date: '2009-01-03',
    sentiment_votes_up_percentage: 95,
    sentiment_votes_down_percentage: 5,
    watchlist_portfolio_users: 1000000,
    market_cap_rank: 1,
    market_data: {
      current_price: { usd: 91827.0 },
      total_value_locked: null,
      mcap_to_tvl_ratio: null,
      fdv_to_tvl_ratio: null,
      roi: null,
      ath: { usd: 73738 },
      ath_change_percentage: { usd: 24.5 },
      ath_date: { usd: '2024-03-14T07:10:36.069Z' },
      atl: { usd: 67.81 },
      atl_change_percentage: { usd: 135400 },
      atl_date: { usd: '2013-07-06T00:00:00.000Z' },
      market_cap: { usd: 1800000000000 },
      market_cap_rank: 1,
      fully_diluted_valuation: { usd: 1918000000000 },
      market_cap_fdv_ratio: 0.94,
      total_volume: { usd: 25000000000 },
      high_24h: { usd: 93600 },
      low_24h: { usd: 90500 },
      price_change_24h: 1200,
      price_change_percentage_24h: 1.89,
      price_change_percentage_7d: 2.5,
      price_change_percentage_14d: 5.2,
      price_change_percentage_30d: 10.5,
      price_change_percentage_60d: 15.8,
      price_change_percentage_200d: 45.2,
      price_change_percentage_1y: 120.5,
      market_cap_change_24h: 34000000000,
      market_cap_change_percentage_24h: 1.89,
      price_change_24h_in_currency: { usd: 1200 },
      price_change_percentage_1h_in_currency: { usd: 0.1 },
      price_change_percentage_24h_in_currency: { usd: 1.89 },
      price_change_percentage_7d_in_currency: { usd: 2.5 },
      price_change_percentage_14d_in_currency: { usd: 5.2 },
      price_change_percentage_30d_in_currency: { usd: 10.5 },
      price_change_percentage_60d_in_currency: { usd: 15.8 },
      price_change_percentage_200d_in_currency: { usd: 45.2 },
      price_change_percentage_1y_in_currency: { usd: 120.5 },
      market_cap_change_24h_in_currency: { usd: 34000000000 },
      market_cap_change_percentage_24h_in_currency: { usd: 1.89 },
      total_supply: 19714218,
      max_supply: 21000000,
      max_supply_infinite: false,
      circulating_supply: 19714218,
      last_updated: new Date().toISOString(),
    },
    status_updates: [],
    last_updated: new Date().toISOString(),
  },
  ethereum: {
    id: 'ethereum',
    symbol: 'eth',
    name: 'Ethereum',
    web_slug: 'ethereum',
    asset_platform_id: null,
    platforms: {},
    detail_platforms: {},
    block_time_in_minutes: 0.2, // ~12-15 seconds
    hashing_algorithm: 'Ethash',
    categories: ['Smart Contract Platform', 'Layer 1'],
    preview_listing: false,
    public_notice: null,
    additional_notices: [],
    description: {
      en: 'Ethereum is a decentralized, open-source blockchain platform that enables developers to build and deploy smart contracts and decentralized applications (dApps). It introduced the concept of programmable blockchain and hosts the second-largest cryptocurrency by market capitalization.',
    },
    links: {
      homepage: ['https://ethereum.org'],
      whitepaper: 'https://ethereum.org/en/whitepaper/',
      blockchain_site: ['https://etherscan.io'],
      official_forum_url: ['https://ethereum-magicians.org'],
      chat_url: [],
      announcement_url: [],
      snapshot_url: null,
      twitter_screen_name: 'ethereum',
      facebook_username: '',
      bitcointalk_thread_identifier: null,
      telegram_channel_identifier: '',
      subreddit_url: 'https://reddit.com/r/ethereum',
      repos_url: {
        github: ['https://github.com/ethereum/go-ethereum'],
        bitbucket: [],
      },
    },
    image: {
      thumb: '',
      small: '',
      large: '',
    },
    country_origin: '',
    genesis_date: '2015-07-30',
    sentiment_votes_up_percentage: 92,
    sentiment_votes_down_percentage: 8,
    watchlist_portfolio_users: 850000,
    market_cap_rank: 2,
    market_data: {
      current_price: { usd: 3147.8 },
      total_value_locked: null,
      mcap_to_tvl_ratio: null,
      fdv_to_tvl_ratio: null,
      roi: {
        times: 80.75,
        currency: 'btc',
        percentage: 7974.99,
      },
      ath: { usd: 4878.26 },
      ath_change_percentage: { usd: -35.48 },
      ath_date: { usd: '2021-11-10T14:24:19.604Z' },
      atl: { usd: 0.432979 },
      atl_change_percentage: { usd: 727157.16 },
      atl_date: { usd: '2015-10-20T00:00:00.000Z' },
      market_cap: { usd: 420000000000 },
      market_cap_rank: 2,
      fully_diluted_valuation: { usd: 420000000000 },
      market_cap_fdv_ratio: 1.0,
      total_volume: { usd: 18000000000 },
      high_24h: { usd: 3159.2 },
      low_24h: { usd: 3115.9 },
      price_change_24h: 26.98,
      price_change_percentage_24h: 0.87,
      price_change_percentage_7d: -2.25,
      price_change_percentage_14d: 1.5,
      price_change_percentage_30d: 8.2,
      price_change_percentage_60d: 12.5,
      price_change_percentage_200d: 35.8,
      price_change_percentage_1y: 95.3,
      market_cap_change_24h: 3800000000,
      market_cap_change_percentage_24h: 0.91,
      price_change_24h_in_currency: { usd: 26.98 },
      price_change_percentage_1h_in_currency: { usd: -0.05 },
      price_change_percentage_24h_in_currency: { usd: 0.87 },
      price_change_percentage_7d_in_currency: { usd: -2.25 },
      price_change_percentage_14d_in_currency: { usd: 1.5 },
      price_change_percentage_30d_in_currency: { usd: 8.2 },
      price_change_percentage_60d_in_currency: { usd: 12.5 },
      price_change_percentage_200d_in_currency: { usd: 35.8 },
      price_change_percentage_1y_in_currency: { usd: 95.3 },
      market_cap_change_24h_in_currency: { usd: 3800000000 },
      market_cap_change_percentage_24h_in_currency: { usd: 0.91 },
      total_supply: 120182788,
      max_supply: null,
      max_supply_infinite: true,
      circulating_supply: 120182788,
      last_updated: new Date().toISOString(),
    },
    status_updates: [],
    last_updated: new Date().toISOString(),
  },

  tether: {
    id: 'tether',
    symbol: 'usdt',
    name: 'Tether',
    web_slug: 'tether',
    asset_platform_id: null,
    platforms: {},
    detail_platforms: {},
    block_time_in_minutes: 0,
    hashing_algorithm: '',
    categories: ['Stablecoin'],
    preview_listing: false,
    public_notice: null,
    additional_notices: [],
    description: {
      en: 'Tether (USDT) is a stablecoin pegged to the US Dollar at a 1:1 ratio. It is one of the most widely used stablecoins in the cryptocurrency market, providing stability and liquidity across multiple blockchain platforms including Ethereum, Tron, and others.',
    },
    links: {
      homepage: ['https://tether.to'],
      whitepaper: 'https://tether.to/en/transparency',
      blockchain_site: [
        'https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7',
      ],
      official_forum_url: [],
      chat_url: [],
      announcement_url: [],
      snapshot_url: null,
      twitter_screen_name: 'Tether_to',
      facebook_username: '',
      bitcointalk_thread_identifier: null,
      telegram_channel_identifier: '',
      subreddit_url: 'https://reddit.com/r/tether',
      repos_url: {
        github: [],
        bitbucket: [],
      },
    },
    image: {
      thumb: '',
      small: '',
      large: '',
    },
    country_origin: '',
    genesis_date: '2014-10-06',
    sentiment_votes_up_percentage: 75,
    sentiment_votes_down_percentage: 25,
    watchlist_portfolio_users: 450000,
    market_cap_rank: 3,
    market_data: {
      current_price: { usd: 1.0 },
      total_value_locked: null,
      mcap_to_tvl_ratio: null,
      fdv_to_tvl_ratio: null,
      roi: null,
      ath: { usd: 1.32 },
      ath_change_percentage: { usd: -24.24 },
      ath_date: { usd: '2018-07-24T00:00:00.000Z' },
      atl: { usd: 0.572521 },
      atl_change_percentage: { usd: 74.68 },
      atl_date: { usd: '2015-03-02T00:00:00.000Z' },
      market_cap: { usd: 140000000000 },
      market_cap_rank: 3,
      fully_diluted_valuation: { usd: 140000000000 },
      market_cap_fdv_ratio: 1.0,
      total_volume: { usd: 85000000000 },
      high_24h: { usd: 1.001 },
      low_24h: { usd: 0.999 },
      price_change_24h: 0.0001,
      price_change_percentage_24h: 0.01,
      price_change_percentage_7d: 0.02,
      price_change_percentage_14d: 0.01,
      price_change_percentage_30d: -0.05,
      price_change_percentage_60d: 0.1,
      price_change_percentage_200d: 0.15,
      price_change_percentage_1y: 0.2,
      market_cap_change_24h: 50000000,
      market_cap_change_percentage_24h: 0.04,
      price_change_24h_in_currency: { usd: 0.0001 },
      price_change_percentage_1h_in_currency: { usd: 0.0 },
      price_change_percentage_24h_in_currency: { usd: 0.01 },
      price_change_percentage_7d_in_currency: { usd: 0.02 },
      price_change_percentage_14d_in_currency: { usd: 0.01 },
      price_change_percentage_30d_in_currency: { usd: -0.05 },
      price_change_percentage_60d_in_currency: { usd: 0.1 },
      price_change_percentage_200d_in_currency: { usd: 0.15 },
      price_change_percentage_1y_in_currency: { usd: 0.2 },
      market_cap_change_24h_in_currency: { usd: 50000000 },
      market_cap_change_percentage_24h_in_currency: { usd: 0.04 },
      total_supply: 140000000000,
      max_supply: null,
      max_supply_infinite: true,
      circulating_supply: 140000000000,
      last_updated: new Date().toISOString(),
    },
    status_updates: [],
    last_updated: new Date().toISOString(),
  },

  solana: {
    id: 'solana',
    symbol: 'sol',
    name: 'Solana',
    web_slug: 'solana',
    asset_platform_id: null,
    platforms: {},
    detail_platforms: {},
    block_time_in_minutes: 0.008, // ~400ms
    hashing_algorithm: 'Proof of History',
    categories: ['Smart Contract Platform', 'Layer 1', 'High Performance'],
    preview_listing: false,
    public_notice: null,
    additional_notices: [],
    description: {
      en: 'Solana is a high-performance blockchain platform designed for decentralized applications and crypto-currencies. It uses a unique Proof of History consensus mechanism combined with Proof of Stake, enabling it to process thousands of transactions per second with low fees.',
    },
    links: {
      homepage: ['https://solana.com'],
      whitepaper: 'https://solana.com/solana-whitepaper.pdf',
      blockchain_site: ['https://explorer.solana.com'],
      official_forum_url: ['https://forums.solana.com'],
      chat_url: ['https://discord.com/invite/pquxPsq'],
      announcement_url: [],
      snapshot_url: null,
      twitter_screen_name: 'solana',
      facebook_username: '',
      bitcointalk_thread_identifier: null,
      telegram_channel_identifier: '',
      subreddit_url: 'https://reddit.com/r/solana',
      repos_url: {
        github: ['https://github.com/solana-labs/solana'],
        bitbucket: [],
      },
    },
    image: {
      thumb: '',
      small: '',
      large: '',
    },
    country_origin: '',
    genesis_date: '2020-03-16',
    sentiment_votes_up_percentage: 88,
    sentiment_votes_down_percentage: 12,
    watchlist_portfolio_users: 320000,
    market_cap_rank: 6,
    market_data: {
      current_price: { usd: 134.29 },
      total_value_locked: null,
      mcap_to_tvl_ratio: null,
      fdv_to_tvl_ratio: null,
      roi: null,
      ath: { usd: 293.31 },
      ath_change_percentage: { usd: -54.22 },
      ath_date: { usd: '2025-01-19T11:15:27.957Z' },
      atl: { usd: 0.500801 },
      atl_change_percentage: { usd: 26727.55 },
      atl_date: { usd: '2020-05-11T19:35:23.449Z' },
      market_cap: { usd: 82000000000 },
      market_cap_rank: 6,
      fully_diluted_valuation: { usd: 95000000000 },
      market_cap_fdv_ratio: 0.86,
      total_volume: { usd: 6400000000 },
      high_24h: { usd: 135.17 },
      low_24h: { usd: 132.68 },
      price_change_24h: 1.55,
      price_change_percentage_24h: 0.99,
      price_change_percentage_7d: 8.8,
      price_change_percentage_14d: 12.5,
      price_change_percentage_30d: 18.3,
      price_change_percentage_60d: 25.7,
      price_change_percentage_200d: 45.2,
      price_change_percentage_1y: 180.5,
      market_cap_change_24h: 840000000,
      market_cap_change_percentage_24h: 1.03,
      price_change_24h_in_currency: { usd: 1.55 },
      price_change_percentage_1h_in_currency: { usd: 0.2 },
      price_change_percentage_24h_in_currency: { usd: 0.99 },
      price_change_percentage_7d_in_currency: { usd: 8.8 },
      price_change_percentage_14d_in_currency: { usd: 12.5 },
      price_change_percentage_30d_in_currency: { usd: 18.3 },
      price_change_percentage_60d_in_currency: { usd: 25.7 },
      price_change_percentage_200d_in_currency: { usd: 45.2 },
      price_change_percentage_1y_in_currency: { usd: 180.5 },
      market_cap_change_24h_in_currency: { usd: 840000000 },
      market_cap_change_percentage_24h_in_currency: { usd: 1.03 },
      total_supply: 617545697,
      max_supply: null,
      max_supply_infinite: false,
      circulating_supply: 563277394,
      last_updated: new Date().toISOString(),
    },
    status_updates: [],
    last_updated: new Date().toISOString(),
  },
};
